oauth2-proxy:
  config:
    existingSecret: oauth2-proxy-secret

    configFile: |-
      reverse_proxy = true
      email_domains = [ "*" ]
      upstreams = [ "static://202" ]
      provider = "github"
      scope = "user:email"
      github_users = "KevinGuilloux"
      cookie_domains = ".k3s-kgu.dev.gnc"
      redirect_url = "https://10.10.10.115/auth/oauth2/callback"
      whitelist_domains = "10.10.10.115"
#      whitelist_domains = "*.k3s-kgu.dev.gnc"

  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - 10.10.10.115
#      - auth.k3s-kgu.dev.gnc
    path: /auth
    annotations:
      cert-manager.io/cluster-issuer: "ca-issuer"
      traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd,default-auth-headers@kubernetescrd
    tls:
      - hosts:
          - auth.k3s-kgu.dev.gnc
        secretName: auth-k3s-kgu-dev-gnc

  redis:
    enabled: false

#  extraEnv:
#    - name: HTTP_PROXY
#      value: http://proxy-web.proxy-dmz.gnc:3128
#    - name: HTTPS_PROXY
#      value: http://proxy-web.proxy-dmz.gnc:3128
#    - name: NO_PROXY
#      value: code-server
